# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: xenial
sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6

before_script:
  - python -V
  - python3 -V
  - ln -s /usr/bin/python3.6 /usr/bin/python
  - R CMD INSTALL .
  - R -e 'autokeras::install_autokeras()'
