# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: xenial
sudo: true

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6
      - libpython3.6-dev

before_install:
  - sudo ln -sf /usr/bin/python3.6 /usr/bin/python
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip install --upgrade --ignore-installed --user travis virtualenv

before_script:
  - R CMD INSTALL .
  - R -e 'autokeras::install_autokeras()'
